version: 0.1
#
#environment_variables:
#  plaintext:
#    CONFIG_FILE: env-details.yml

phases:
  install:
    commands:
#      - pip uninstall lxml
#      - sudo apt-get install python3-venv
      - pip install virtualenv
      - virtualenv venv --no-site-packages --python=python3.6
      - source venv/bin/activate
      - pip install -r requirements.txt -t ./app/
#  pre_build:
#    commands:
#      - echo "Validating config file $CONFIG_FILE"
#      - pwd
#      - pip install pyquery requests lxml -t ./
#      - ls -l
#      - yamllint $CONFIG_FILE
#
#  build:
#    commands:
#
#      # Package our application with AWS SAM
#      - aws cloudformation package --template-file template.yml --s3-bucket ${S3_BUCKET} --output-template-file packaged.yml

artifacts:
  files:
    - '**/*'
#    - 'app/**'
  base-directory: app
