version: 0.1
#
#environment_variables:
#  plaintext:
#    CONFIG_FILE: env-details.yml

phases:
  install:
    commands:
#      - pip uninstall lxml
#      - sudo apt-get install python3-venv
#      - sudo dpkg-reconfigure bash
      - pip install virtualenv
      - pip --version
#      - sudo apt-get install python3-venv
      - virtualenv venv --no-site-packages --python=python3.5
      - . venv/bin/activate
      - pip install -r requirements.txt -t ./app/
  pre_build:
    commands:
      - pwd
      - ls -l
      - aws s3 cp s3://dick-code-lambda/lxml.zip ./
      - ls -l
#      - rm -rf lxml*/
#  build:
#    commands:
#
#      # Package our application with AWS SAM
#      - aws cloudformation package --template-file template.yml --s3-bucket ${S3_BUCKET} --output-template-file packaged.yml

artifacts:
  files:
    - '**/*'
#    - 'app/**'
  base-directory: app
