version: 0.1
#
#environment_variables:
#  plaintext:
#    CONFIG_FILE: env-details.yml

phases:
  install:
    commands:
#      - pip install --upgrade pip
#      - pip install pyyaml --upgrade
      - echo pip install yamllint --upgrade
  pre_build:
    commands:
      - echo "Validating config file $CONFIG_FILE"
      - pwd
#      - pip install pyquery requests lxml -t ./
      - ls -l
#      - yamllint $CONFIG_FILE
  build:
    commands:
      - pip install pyquery requests lxml -t ./

  post_build:
    commands:
      -ls -l
#
#artifacts:
#  files:
#    - build-output.zip