AWSTemplateFormatVersion: 2010-09-09
Description: My Lambda function

Parameters:
  CapitalizedProjectName:
    Type: String
    Default: MyLambdaProject
  DeploymentPackageKey:
    Type: String
    Description: An S3 object key pointing of a ZIP file, an archive of everything that is needed to run the Lambda function. It is the output of the Build stage of the pipeline.

Resources:
  LambdaRunnerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          'Fn::ImportValue': !Sub '${CapitalizedProjectName}PipelineArtifactsBucket'
        S3Key: !Ref DeploymentPackageKey
      FunctionName: my-lambda-function
      Handler: main.handler
      Role: !GetAtt LambdaRunnerRole.Arn
      Runtime: python3.5

Outputs:
  LambdaFunction:
    Description: The ARN of the created Lambda function
    Value: !GetAtt LambdaFunction.Arn
